### ISSUE TITLE
Split calls for database and system level views

### ISSUE THREAD

**Issue by wsmelton** [microsoft/azure-sql-tips#33] opened 2021-01-14 14:25 UTC
In many environments, an admin is not an admin of the whole Azure SQL server and only the DB; or a developer wants to validate the database level items only.

The script as-is fails if **any** system view is not accessible without allowing us to run checks against a database. Splitting these into two catch blocks and simply show the checks that failed due to permissions will still offer users the ability to see improvements/things to fix instead of not knowing any of them.

**Comment by dimitri-furman** [comment] 2021-01-14 15:37
Duplicate of #34

**Closed by dimitri-furman** 2021-01-14 15:37 UTC
